#:schema node_modules/wrangler/config-schema.json
name = "logpush-custom-worker"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

# your account id, found in the Cloudflare dashboard.
account_id = "<UPDATE_ME>"

# set to true to generate a dev domain
workers_dev = true

# if you want a custom domain on your zone, update the following to
# create the DNS record when this worker gets deployed
routes = [
  { pattern = "logpush-worker.yourzone.com", custom_domain = true }
]

[vars]
AUTH_TOKEN = "<UPDATE_ME> use for dev only, for production use workers secrets"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
# Good for debugging but should disable in production
[observability]
enabled = true
